/**
 * Google Play In-App Review integration.
 *
 * When the app runs inside the Android package generated by PWABuilder
 * (Trusted Web Activity), the Play In-App Review API is exposed to the web
 * layer through a JavaScript bridge. We call it when available and fall back
 * to the Play Store listing in a normal browser.
 */

const PACKAGE_NAME = "scientific.calculator.cm";
const PLAY_URL = `https://play.google.com/store/apps/details?id=${PACKAGE_NAME}`;

const STORAGE_KEY = "nume.review";
const MIN_CALCULATIONS = 12;
const COOLDOWN_MS = 1000 * 60 * 60 * 24 * 60; // 60 days

type ReviewBridge = {
  requestReview?: () => void | Promise<void>;
  requestInAppReview?: () => void | Promise<void>;
};

type ReviewState = { count: number; lastPrompt: number; done: boolean };

declare global {
  interface Window {
    AndroidReview?: ReviewBridge;
    PlayReview?: ReviewBridge;
  }
}

const readState = (): ReviewState => {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return { count: 0, lastPrompt: 0, done: false, ...JSON.parse(raw) };
  } catch {
    /* ignore */
  }
  return { count: 0, lastPrompt: 0, done: false };
};

const writeState = (state: ReviewState) => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    /* ignore */
  }
};

const getBridge = (): ReviewBridge | undefined => {
  if (typeof window === "undefined") return undefined;
  const bridge = window.AndroidReview ?? window.PlayReview;
  if (!bridge) return undefined;
  return typeof bridge.requestReview === "function" ||
    typeof bridge.requestInAppReview === "function"
    ? bridge
    : undefined;
};

export const isInAppReviewAvailable = () => Boolean(getBridge());

/** Directly ask Play for the in-app review sheet (or open the store listing). */
export const requestInAppReview = async (): Promise<boolean> => {
  const bridge = getBridge();
  try {
    if (bridge?.requestReview) {
      await bridge.requestReview();
      return true;
    }
    if (bridge?.requestInAppReview) {
      await bridge.requestInAppReview();
      return true;
    }
  } catch {
    /* fall through to the store listing */
  }

  if (typeof window !== "undefined") {
    window.open(PLAY_URL, "_blank", "noopener,noreferrer");
    return false;
  }
  return false;
};

/**
 * Count a successful calculation and, once the user has clearly got value from
 * the app, ask Play to show the review sheet at most once per cooldown window.
 * Play itself decides whether the sheet is actually displayed.
 */
export const noteSuccessfulCalculation = () => {
  const state = readState();
  state.count += 1;

  const eligible =
    !state.done &&
    state.count >= MIN_CALCULATIONS &&
    Date.now() - state.lastPrompt > COOLDOWN_MS &&
    isInAppReviewAvailable();

  if (eligible) {
    state.lastPrompt = Date.now();
    state.done = true;
    writeState(state);
    void requestInAppReview();
    return;
  }

  writeState(state);
};

export const playStoreUrl = PLAY_URL;
