name: Create Org Keystore
on: workflow_dispatch
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - run: keytool -genkeypair -v -keystore upload-keystore.jks -alias upload -storepass changeit123 -keypass changeit123 -dname "CN=Joy Org" -keyalg RSA -keysize 2048 -validity 10000
    - run: base64 upload-keystore.jks | tr -d '\n' > keystore.txt
    - uses: actions/upload-artifact@v4
      with: { name: org-keystore-base64, path: keystore.txt }
